#!/usr/bin/env zsh

# General behaviour

# Do not require cd when just a path is given
setopt autocd
# Case-insensitive globbing
setopt nocaseglob

# History
setopt sharehistory
setopt appendhistory
setopt incappendhistory
setopt histexpiredupsfirst
setopt histignoredups
setopt histfindnodups
setopt histreduceblanks

# Correction
setopt correct
setopt correctall

# Prompt
setopt promptsubst

# Load version control information
autoload -Uz vcs_info
precmd_functions+=(vcs_info)

# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git:*' formats ' %r:%b'

# Completions

# partial completion suggestions
zstyle ':completion:*' list-colors
zstyle ':completion:*' list-suffixes
zstyle ':completion:*' expand prefix suffix

fpath=(/usr/local/share/zsh-completions $fpath)
autoload -Uz compinit && compinit

SCRIPTS="${HOME}/.shell"

source "${SCRIPTS}/common/env.sh"
source "${SCRIPTS}/common/colours.sh"
source "${SCRIPTS}/common/aliases.sh"
# source "${SCRIPTS}/oh-my-zsh.zsh"

# Prompt
PROMPT='%(!.%F{red}!%f .)%(?.%F{green}.%F{red}%f) %F{white}[%1~]%f %F{yellow} %f '
RPROMPT='%F{yellow}${vcs_info_msg_0_}%f'

if [ -n "${SSH_CLIENT+1}" ]; then
  PROMPT="歷 ${PROMPT}"
fi

cd .
